fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

wadii_first:
    resource: "@WadiiFirstBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
