<?php

namespace AppBundle\Repository;

/**
 * CompteSocialeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteSocialeRepository extends \Doctrine\ORM\EntityRepository
{
}
