<?php

namespace AppBundle\Repository;

/**
 * EtudiantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantsRepository extends \Doctrine\ORM\EntityRepository
{
}
